require(File.expand_path('./test.rb', File.dirname(__FILE__)))
require(File.expand_path('./src/cell.test.rb', File.dirname(__FILE__)))
require(File.expand_path('./src/pattern.test.rb', File.dirname(__FILE__)))
require(File.expand_path('./src/grid.test.rb', File.dirname(__FILE__)))
require(File.expand_path('./src/util.test.rb', File.dirname(__FILE__)))
require(File.expand_path('./src/wave.test.rb', File.dirname(__FILE__)))
